[versions]
agp = "9.3.1"
annotation = "1.10.0"
junit = "4.13.2"
ktfmt = "0.27.0"
libcxx = "29.0.14206865"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
junit = { module = "junit:junit", version.ref = "junit" }
libcxx = { module = "org.lsposed.libcxx:libcxx", version.ref = "libcxx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
